package ir.ac.kntu.pages;

public enum PageTitle {
    WELCOME, EXIT,
    CUSTOMER_LOGIN, CUSTOMER_REGISTER,
    SELLER_LOGIN, SELLER_REGISTER,
    CUSTOMER_HOME, SELLER_HOME, SUPPORTER_HOME,
    SELLER_PRODUCT,
    CUSTOMER_WALLET, SELLER_WALLET, TRANSACTIONS, RECEIPT,
    PROFILE, CART, STORE, LOGOUT, EDIT_PROFILE, ADDRESSES,
    SUPPORTER_LOGIN, SUPPORTER_RECEIPT, SUPPORTER_REQUEST, AUTHENTICATION, CUSTOMER_REQUEST, COMMENTS, SELLER_NOT, SELLER_INFO, MANAGER_HOME, MANAGER_LOGIN, SEARCH, NOTIFICATIONS, PLUS_MEMBERSHIP, NOTIF_REQUEST, PRODUCT, MANAGE_USERS;
}
